name: cuidados_fibrilacao_atrial
description: Aplicativo para auxílio de pacientes com FA

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

#adicionar a referencia dos icones <a href="https://www.flaticon.com/free-icons/medical-report" title="medical-report icons">Medical-report icons created by Freepik - Flaticon</a>
#  Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
#  Framework • revision e3c29ec00c (1 year, 4 months ago) • 2022-09-14 08:46:55 -0500
#  Engine • revision a4ff2c53d8
#  Tools • Dart 2.18.1 • DevTools 2.15.0

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  provider: ^6.0.2
  rxdart: ^0.27.3
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  image_picker: ^0.8.4+11
  photo_view: ^0.13.0
  fl_chart: ^0.55.0
  badges: ^2.0.2
  flutter_local_notifications: ^9.4.0
  google_fonts: ^2.3.1
  modal_bottom_sheet: ^2.1.2
  workmanager: ^0.5.1
  shared_preferences: ^2.0.18
  flutter_launcher_icons: ^0.12.0
  url_launcher: ^6.1.11


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "ico/app-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"
#overlay_support: ^1.2.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - ico/exame-de-saude.png
    - ico/medicacao.png
    - ico/orientacoes-pessoais.png
    - ico/medical-checkup.png
    - ico/clinic-history.png
    - ico/examination.png
    - ico/heart.png
    - ico/telemedicine.png
    - ico/check-up.png
    - ico/score.png
    - ico/patient.png
    - ico/nurse_ori.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages